"""
APPS Dataset Loader

Loads problems from the APPS (Automated Programming Problem Solving) dataset.
Dataset location: data/APPS/train/ and data/APPS/test/
"""

from dataclasses import dataclass, asdict
from typing import List, Optional, Dict, Any
from pathlib import Path
import json
import os


# Default APPS data path (relative to project root)
APPS_DATA_PATH = Path(__file__).parent.parent.parent / "data" / "APPS"

# Pre-filtered problems file (generated by scripts/filter_apps.py)
FILTERED_PROBLEMS_PATH = APPS_DATA_PATH / "filtered_problems.json"


@dataclass
class APPSProblem:
    """Reference to an APPS problem"""
    problem_id: str          # e.g., "0000", "1234"
    difficulty: str          # "introductory" | "interview" | "competition"
    question: str            # Problem text
    solutions: List[str]     # Reference solutions
    test_cases: Dict[str, Any]  # input_output.json content
    url: Optional[str] = None   # Source URL (if available)

    def to_dict(self) -> dict:
        """Convert to JSON-serializable dict"""
        return asdict(self)


def dict_to_apps_problem(d: dict) -> APPSProblem:
    """Convert dict to APPSProblem"""
    return APPSProblem(
        problem_id=d["problem_id"],
        difficulty=d["difficulty"],
        question=d["question"],
        solutions=d.get("solutions", []),
        test_cases=d.get("test_cases", {}),
        url=d.get("url")
    )


class APPSLoader:
    """
    Loads and manages APPS problems from the filesystem.

    Usage:
        loader = APPSLoader()
        problems = loader.list_problems(difficulty=["interview"], limit=10)
        problem = loader.load_problem("0042")
    """

    def __init__(self, data_path: Optional[Path] = None, split: str = "train", use_filtered: bool = True):
        """
        Initialize the APPS loader.

        Args:
            data_path: Path to APPS data directory. Defaults to data/APPS/
            split: "train" or "test"
            use_filtered: If True, only load problems from filtered_problems.json
        """
        self.data_path = data_path or APPS_DATA_PATH
        self.split = split
        self.split_path = self.data_path / split
        self.use_filtered = use_filtered

        # Cache for loaded problems
        self._problem_cache: Dict[str, APPSProblem] = {}
        self._index_cache: Optional[List[Dict[str, str]]] = None

        # Load pre-filtered problem IDs
        self._filtered_ids: Optional[set] = None
        self._filter_stats: Optional[Dict[str, Any]] = None
        if use_filtered:
            self._load_filtered_ids()

    def _load_filtered_ids(self) -> None:
        """Load pre-filtered problem IDs from JSON file"""
        if not FILTERED_PROBLEMS_PATH.exists():
            print(f"Warning: Filtered problems file not found: {FILTERED_PROBLEMS_PATH}")
            print("Run 'python scripts/filter_apps.py' to generate it.")
            print("Falling back to loading all problems.")
            self.use_filtered = False
            return

        try:
            with open(FILTERED_PROBLEMS_PATH, 'r') as f:
                data = json.load(f)

            self._filtered_ids = set(data.get("problem_ids", []))
            self._filter_stats = data.get("stats", {})
            print(f"Loaded {len(self._filtered_ids)} pre-filtered problems")
        except (json.JSONDecodeError, IOError) as e:
            print(f"Warning: Failed to load filtered problems: {e}")
            print("Falling back to loading all problems.")
            self.use_filtered = False

    def _get_problem_path(self, problem_id: str) -> Path:
        """Get the filesystem path for a problem"""
        return self.split_path / problem_id

    def _load_problem_files(self, problem_id: str) -> Optional[APPSProblem]:
        """Load a problem from its directory"""
        problem_path = self._get_problem_path(problem_id)

        if not problem_path.exists():
            return None

        try:
            # Load metadata
            metadata_path = problem_path / "metadata.json"
            if metadata_path.exists():
                with open(metadata_path, 'r') as f:
                    metadata = json.load(f)
            else:
                metadata = {"difficulty": "unknown"}

            # Load question
            question_path = problem_path / "question.txt"
            if question_path.exists():
                with open(question_path, 'r') as f:
                    question = f.read()
            else:
                question = ""

            # Load solutions
            solutions_path = problem_path / "solutions.json"
            if solutions_path.exists():
                with open(solutions_path, 'r') as f:
                    solutions = json.load(f)
            else:
                solutions = []

            # Load test cases
            io_path = problem_path / "input_output.json"
            if io_path.exists():
                with open(io_path, 'r') as f:
                    test_cases = json.load(f)
            else:
                test_cases = {}

            return APPSProblem(
                problem_id=problem_id,
                difficulty=metadata.get("difficulty", "unknown"),
                question=question,
                solutions=solutions if isinstance(solutions, list) else [],
                test_cases=test_cases,
                url=metadata.get("url")
            )
        except Exception as e:
            print(f"Error loading problem {problem_id}: {e}")
            return None

    def load_problem(self, problem_id: str) -> Optional[APPSProblem]:
        """
        Load a single problem by ID.

        Args:
            problem_id: Problem ID (e.g., "0000", "1234")

        Returns:
            APPSProblem or None if not found
        """
        # Check cache first
        if problem_id in self._problem_cache:
            return self._problem_cache[problem_id]

        problem = self._load_problem_files(problem_id)
        if problem:
            self._problem_cache[problem_id] = problem

        return problem

    def _build_index(self) -> List[Dict[str, str]]:
        """Build an index of problems (filtered if use_filtered=True)"""
        if self._index_cache is not None:
            return self._index_cache

        index = []

        if not self.split_path.exists():
            return index

        # List all problem directories
        for entry in sorted(os.listdir(self.split_path)):
            # Skip if using filtered list and this ID is not in it
            if self.use_filtered and self._filtered_ids and entry not in self._filtered_ids:
                continue

            problem_path = self.split_path / entry
            if not problem_path.is_dir():
                continue

            # Load just metadata for indexing
            metadata_path = problem_path / "metadata.json"
            if metadata_path.exists():
                try:
                    with open(metadata_path, 'r') as f:
                        metadata = json.load(f)
                    index.append({
                        "problem_id": entry,
                        "difficulty": metadata.get("difficulty", "unknown"),
                        "url": metadata.get("url")
                    })
                except Exception:
                    index.append({
                        "problem_id": entry,
                        "difficulty": "unknown"
                    })
            else:
                index.append({
                    "problem_id": entry,
                    "difficulty": "unknown"
                })

        self._index_cache = index
        return index

    def list_problems(
        self,
        difficulty: Optional[List[str]] = None,
        limit: Optional[int] = None,
        offset: int = 0
    ) -> List[Dict[str, str]]:
        """
        List problems with optional filtering.

        Args:
            difficulty: Filter by difficulty levels (e.g., ["interview", "competition"])
            limit: Maximum number of problems to return
            offset: Skip this many problems (for pagination)

        Returns:
            List of problem metadata dicts with 'problem_id' and 'difficulty'
        """
        index = self._build_index()

        # Filter by difficulty
        if difficulty:
            index = [p for p in index if p["difficulty"] in difficulty]

        # Apply offset
        if offset > 0:
            index = index[offset:]

        # Apply limit
        if limit is not None:
            index = index[:limit]

        return index

    def count_problems(self, difficulty: Optional[List[str]] = None) -> int:
        """
        Count total problems matching filters.

        Args:
            difficulty: Filter by difficulty levels

        Returns:
            Number of matching problems
        """
        index = self._build_index()

        if difficulty:
            return len([p for p in index if p["difficulty"] in difficulty])

        return len(index)

    def get_difficulties(self) -> Dict[str, int]:
        """
        Get a count of problems by difficulty level.

        Returns:
            Dict mapping difficulty to count
        """
        index = self._build_index()
        counts: Dict[str, int] = {}

        for p in index:
            diff = p["difficulty"]
            counts[diff] = counts.get(diff, 0) + 1

        return counts

    def load_problems(self, problem_ids: List[str]) -> List[APPSProblem]:
        """
        Load multiple problems by ID.

        Args:
            problem_ids: List of problem IDs

        Returns:
            List of APPSProblem objects (skips any not found)
        """
        problems = []
        for pid in problem_ids:
            problem = self.load_problem(pid)
            if problem:
                problems.append(problem)
        return problems

    def validate_problem_ids(self, problem_ids: List[str]) -> Dict[str, bool]:
        """
        Check which problem IDs exist and are valid (in filtered list if enabled).

        Args:
            problem_ids: List of problem IDs to check

        Returns:
            Dict mapping problem_id to exists (True/False)
        """
        results = {}
        for pid in problem_ids:
            # Check if in filtered list (if filtering enabled)
            if self.use_filtered and self._filtered_ids and pid not in self._filtered_ids:
                results[pid] = False
                continue
            problem_path = self._get_problem_path(pid)
            results[pid] = problem_path.exists()
        return results

    def get_filter_stats(self) -> Optional[Dict[str, Any]]:
        """
        Get statistics from the pre-filtering process.

        Returns:
            Dict with filter stats or None if not using filtered list
        """
        return self._filter_stats

    def is_problem_valid(self, problem_id: str) -> bool:
        """
        Check if a problem ID is valid (in filtered list if enabled).

        Args:
            problem_id: Problem ID to check

        Returns:
            True if valid, False otherwise
        """
        if self.use_filtered and self._filtered_ids:
            return problem_id in self._filtered_ids
        return self._get_problem_path(problem_id).exists()


# Global loader instance (lazily initialized)
_loader: Optional[APPSLoader] = None


def get_apps_loader(split: str = "train") -> APPSLoader:
    """Get the global APPS loader instance"""
    global _loader
    if _loader is None or _loader.split != split:
        _loader = APPSLoader(split=split)
    return _loader
